[project]
name = "Knowledge-Graph-Engine"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "silvaengine-utility",
    "silvaengine-dynamodb-base",
    "graphene",
    "neo4j",
    "neo4j-graphrag",
    "openai",
    "numpy",
    "openpyxl",
    "python-dotenv",
    "pendulum",
    "promise",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
typeCheckingMode = "basic"
reportCallIssue = "none"
reportArgumentType = "none"
reportIndexIssue = "none"
reportAttributeAccessIssue = "none"
reportOptionalMemberAccess = "none"
reportGeneralTypeIssues = "none"
reportOptionalSubscript = "none"
reportAssignmentType = "none"
reportOptionalCall = "none"
